### ISSUE TITLE
Installation quirks

### ISSUE THREAD

**Issue by gracecodes144** [chop-dbhi/schema-registry#1]
- [x] Needs a `glide.yaml` and `glide.lock` for `make install` or `make setup` to work.
- [x] `make tls` references a file at `$(GOROOT)/src/crypto/tls/generate_cert.go` which there is no recipe to create. Also, I think maybe you mean `GOPATH`?

**Comment by gracecodes144** [comment]
Branch `issue-1` adds the dependency management, but I don't know what to do about the second item above. @bruth?

**Comment by bruth** [comment]
Fixed in latest push. `$(go env GOROOT)` is safer.

**Comment by bruth** [comment]
Thanks, I just pushed what I already had in my repo since I know those versions work.
